repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: end-of-file-fixer
      files: .*\.*.py
    - id: trailing-whitespace
      files: .*\.*.py
    - id: debug-statements
    - id: check-ast
    - id: check-added-large-files
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: requirements-txt-fixer
      args:
        - requirements.txt
        - requirements-dev.txt

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
