language: python

sudo: false

env:
  global:
     secure: "n2fDU3WQjw781S8p1qUVAOIbNay991tk0LiiKZkYPJFUxEUT23yA11i/XODKRdoCuLS7gNfBb1P9QWNXQ9liHIRFzCbYRBRvUseHnkAraTBg3Wq2dDikheUQO82S5TMlttmCXJHaqQLdK3YxBqJdc2FitzxqD0/qn9sSmbfTD5MCAymcFWtqRrLyb4PbnmlJvL2EgFQI9AaZq59WDwo04Gw+tDvBn7krb9HQ8ATzw+YVgIO65xk6TXMPqg0NAnkPmYBf4E39ewyeBvPGbgngvk47zWxQ2GO18Au095P+dk6mykmtjsEf68XrobF+bZyz4Em0IcTP8pGeuvkgRhFysNUiW9KXH+UfhIv9MU1Fx4Q/229d2jPYy0xD6IvG9JW9m7bZmBUp6to7uqDnfxnrlxmTKf7CN/M0qpFSIyqXZEfNye4LlvnTOBJh5XkfZnBHLpwptacMlS5m1pjOWYbSUSGUDebqtQTBDaF7g8EcXMkUKw6nMXE1uTvDM7kcSvBNBaVQh5ammZLn2y6rqfZR0NK9vyGGfl1N+axe+U48iRpFBDs3Pq/IeSWvPVajbpR/kIjstu9ybu6qQPq1BlozvbPEuVGNUAja1jAWP/v3YNbJtWl2bWviyLw7/NWC5W95TPLLFUP1p6nqf3AkiZPjpAVmhC2lY1R9CfotSXD0Bo0="

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TEST_TARGET=default
    - python: 3.5
      env: TEST_TARGET=default
    - python: 3.6
      env: TEST_TARGET=default
    - python: 3.6
      env: TEST_TARGET=coding_standards
    - python: 3.6
      env: TEST_TARGET=docs
  allow_failures:
    - python: 3.6
      env: TEST_TARGET=coding_standards
    - python: 3.6
      env: TEST_TARGET=docs

before_install:
  # Install miniconda
  # -----------------
  - export CONDA_BASE=https://repo.continuum.io/miniconda/Miniconda3
  - export MINICONDA_VERSION=latest
  - wget ${CONDA_BASE}-${MINICONDA_VERSION}-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Create the basic testing environment
  # ------------------------------------
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set show_channel_urls True
  - conda config --add create_default_packages pip
  - conda update --quiet conda

  # Add 3rd party channels
  # ------------------------------------
  - conda config --add channels conda-forge
  - conda config --add channels axiom-data-science

  # Create our environment
  # ------------------------------------
  - ENV_NAME='test-environment'
  - conda create --quiet -n $ENV_NAME python=$TRAVIS_PYTHON_VERSION
  - source activate $ENV_NAME

  # Install testing requirements
  # ------------------------------------
  - conda install --file requirements.txt --file pocean/tests/requirements.txt
  - conda list --export

# Test source distribution.
install:
  - python setup.py sdist && version=$(python setup.py --version) && pushd dist && pip install pocean-core-${version}.tar.gz && popd

script:
  - set -e

  - if [[ $TEST_TARGET == 'default' ]]; then
      py.test --disable-warnings ;
    fi

  - if [[ $TEST_TARGET == "coding_standards" ]]; then
      py.test --disable-warnings --pep8 -m pep8 ;
      py.test --disable-warnings --flakes -m flakes ;
    fi

  - if [[ $TEST_TARGET == 'docs' ]]; then
      ./docs/deploy.sh ;
    fi

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_TAG" != "" ] && [ "$TEST_TARGET" == "default" ]; then
      conda install -n root conda-build anaconda-client ;
      conda build conda-recipe --python $TRAVIS_PYTHON_VERSION ;
      anaconda -t $ANACONDA_TOKEN upload --force -u axiom-data-science $HOME/miniconda/**/pocean-core-*.tar.bz2 ;
    fi

deploy:
  provider: releases
  api_key:
    secure: cvbHcXSGGwwcx50E+66M+ij9RqRgNqD6q7gNGpA/UTbxXdZoXqucbino1t0TVto0OV/ZXJMqbmqe8TGIjHOg8k8UpEYWHZw6etbIM/VpD1KHqqyiWp2GSu6E59FeHj3w93X4QOl4wUpVJN1u24e+Gd3f492aupnjFHNetdbN38TI29S8KG7RBQQ9VX1je29BwLNrC5XI4OwCXS4cV6DdWedBD5W7dGNkyjgj+HV0SOTCO/VRDsHTZJMyAqCYf7esH5/vBCY9vEWVvUwXPFszcy8VBCyVQsgguWkwYQBQvxD8MXzLA24L7b1d8Ec9X04K5EyJrcEEyIA4BfammoehuRFoSfLxx5pGZfU9kRE0YbiidJ0OdkjUdorSUoSHNSpgz/jOJZxjJuS8d+kVUkvQ0Ksfs2GV07weCA3hlwI1BFDa58CCziNg8Dw4y0lnuF0Fx5+b/DB+ISFhJuI+xa3ZtT6ZgY2hGHKm9qBSwF3KUk4dRHManEYlU87rnlZRP8RwXwB4At3qO3qR48glsrKBQRGXcqvtcGvs9Nenp5L1h+ChkjtBIw1qd9/ZZpqkQec7o0h2AwglOClAz+j9d3rVuqFUcuMLZ1OU8XdMX2JfRgL1Unr5J5QSbVBhes/2nXsMWmrcFTJzk11dBcP65H4URGJD7aGS16rjOHubxY/ntHk=
  on:
    tags: true
