site_name: pocean-core
pages:
  - Home: index.md

theme: mkdocs

site_description: A python framework for working with met-ocean data
site_url: https://pyoceans.github.io/pocean-core
repo_url: https://github.com/pyoceans/pocean-core
site_author: Kyle Wilcox
docs_dir: docs
site_dir: _site
markdown_extensions:
  - extra
  - smarty
  - math
  - markdown_checklist.extension
