package:
  name: pocean-core
  version: "1.9.3"

source:
  path: ../

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python
    - netcdf4
    - numpy >=1.15
    - pandas >=0.24,<1.0
    - pygc >=1.2.0
    - python-dateutil
    - pytz
    - shapely
    - simplejson
    - six
    - cftime >=1.2.1

test:
  source_files:
    - pocean
  requires:
    - pytest
  imports:
    - pocean
    - pocean.dsg
    - pocean.grid
    - pocean.tests
  commands:
    - py.test pocean

about:
  home: https://github.com/pyoceans/pocean-core
  license: MIT
  summary: 'A python framework for working with met-ocean data.'
